const paragraphData=[
{chapter:1,number:7,title:'Успешные и безуспешные реформы французских королей',search:'Франция Людовик XV Людовик XVI Мопу Тюрго парламенты дворянство мантии собрание нотаблей налоги реформы Семилетняя война Генеральные штаты 1749 1760 1770 1774 1776',html:`
<div class="important"><strong>Главная проблема Франции:</strong> страна быстро богатела, но государственная казна постоянно испытывала нехватку денег. Основные налоги платило третье сословие, а привилегированные дворянство и духовенство были во многом освобождены от них. Попытки изменить эту систему встречали сильное сопротивление.</div>
<h3>1. Богатая страна — бедное государство</h3>
<p>Экономика Франции росла: расширялась <strong>колониальная и атлантическая торговля</strong>, развивались промышленность, тяжёлая индустрия и сельское хозяйство. Строились дороги, мосты и каналы. Но расходы государства, особенно на армию и войны, оставались огромными.</p>
<p>Французское общество делилось на три сословия. <strong>Духовенство и дворянство</strong> были привилегированными и не платили главный прямой налог с земли. Основная налоговая нагрузка ложилась на <strong>третье сословие</strong>.</p>
<h3>2. Реформы Людовика XV</h3>
<p>В <span class="date">1749 г.</span> Людовик XV ввёл налог в размере 5% с доходов для всех сословий. Привилегированные сословия выступили против, а духовенство добилось освобождения от налога. Поэтому реформа потеряла главное — <strong>всеобщность</strong>.</p>
<p>После Семилетней войны была проведена <strong>военная реформа</strong>: улучшили обучение солдат и офицеров, укрепили дисциплину и реорганизовали артиллерию. Боеспособность армии выросла.</p>
<h3>3. Судебная реформа канцлера Мопу</h3>
<p>Парламенты могли тормозить королевские законы, отказываясь их регистрировать. Канцлер <strong>Рене Никола де Мопу</strong> ограничил их влияние, ликвидировал старые должности и создал новые суды с назначаемыми королём судьями.</p>
<div class="important"><strong>Результат реформы Мопу:</strong> судопроизводство стало эффективнее и дешевле. Но после смерти Людовика XV в <span class="date">1774 г.</span> Людовик XVI отменил реформу и восстановил старые парламенты.</div>
<h3>4. Реформы Тюрго при Людовике XVI</h3>
<p>Экономист <strong>Анн Робер Жак Тюрго</strong> выступал за уменьшение вмешательства государства в экономику и ввёл свободную торговлю зерном. Неурожай вызвал рост цен на хлеб и беспорядки — «мучную войну».</p>
<p>Тюрго предложил <strong>всесословный налог с землевладельцев</strong>. Привилегированные сословия и парламенты выступили против, и в <span class="date">1776 г.</span> Тюрго был отправлен в отставку.</p>
<h3>5. Финансовый кризис</h3>
<p>Участие Франции в Войне за независимость США увеличило государственный долг. В <span class="date">1787 г.</span> правительство снова предложило бессословный поземельный налог, но <strong>собрание нотаблей</strong> его не поддержало.</p>
<p>Неурожаи 1787–1788 гг., рост цен на хлеб, закрытие предприятий и безработица усилили кризис. В итоге Людовик XVI объявил о созыве <strong>Генеральных штатов в 1789 г.</strong></p>
<div class="terms"><h3>🔍 Термины и определения</h3><p><strong>Парламенты во Франции</strong> — высшие судебные учреждения, регистрировавшие королевские законы и способные сопротивляться их проведению.</p><p><strong>«Дворянство мантии»</strong> — судебная аристократия, занимавшая должности в парламентах и других судах.</p><p><strong>Собрание нотаблей</strong> — собрание наиболее влиятельных представителей дворянства, высшего духовенства и верхушки третьего сословия, созываемое королём.</p></div>
<div class="people"><h3>👤 Личности</h3><p><strong>Людовик XV (1715–1774)</strong> — король Франции; при нём предпринимались налоговая и военная реформы, а Мопу провёл судебную реформу.</p><p><strong>Рене Никола де Мопу (1714–1792)</strong> — канцлер, ограничивший влияние парламентов и реформировавший судебную систему.</p><p><strong>Людовик XVI (1774–1792)</strong> — король Франции; отменил реформу Мопу, затем пытался провести преобразования через министров-реформаторов.</p><p><strong>Анн Робер Жак Тюрго (1727–1781)</strong> — экономист и глава правительства в 1774–1776 гг.; сторонник свободной торговли и налоговой реформы.</p></div>
<div class="world-dates"><h3>📅 Даты · Мир</h3><p><span class="date">1749 г.</span> — налоговая реформа Людовика XV.</p><p><span class="date">1760-е гг.</span> — военная реформа Людовика XV.</p><p><span class="date">1770–1774 гг.</span> — судебная реформа канцлера Мопу.</p><p><span class="date">1774–1776 гг.</span> — реформы Тюрго.</p></div>
<div class="conclusion">Французские короли пытались сделать налогообложение справедливее и укрепить государство, но привилегированные сословия и парламенты защищали свои преимущества. Неудачи реформ усилили финансовый и политический кризис.</div>
<div class="answers"><h3>Вопросы в конце §7</h3>
<div class="qa"><div class="q">1. Что обеспечивало экономический рост Франции во второй половине XVIII в.?</div><div class="answer">Расширение колониальной и атлантической торговли, развитие промышленности и тяжёлой индустрии, применение новых технологий, рост сельского хозяйства и строительство дорог, мостов и каналов.</div></div>
<div class="qa"><div class="q">2. Можно ли назвать Людовика XV и Людовика XVI просвещёнными монархами? Обоснуйте свой ответ.</div><div class="answer">Частично. Они пытались проводить реформы, рационализировать управление и налоги, а при них работали министры-реформаторы. Но короли сохраняли абсолютную власть и часто отступали перед сопротивлением привилегированных сословий.</div></div>
<div class="qa"><div class="q">3. Почему военная реформа Людовика XV оказалась успешнее налоговой?</div><div class="answer">Военная реформа не лишала привилегированные сословия их налоговых преимуществ и поэтому встретила меньше сопротивления. Налоговая реформа напрямую затрагивала их материальные интересы.</div></div>
<div class="qa"><div class="q">4. Что общего было в налоговых реформах Людовика XV и Людовика XVI? Почему они потерпели неудачу и к каким последствиям это привело?</div><div class="answer">Обе реформы пытались распределить налоги между сословиями справедливее и вывести государство из финансового кризиса. Привилегированные сословия и парламенты сопротивлялись изменениям. Неудачи реформ усилили кризис и приблизили созыв Генеральных штатов.</div></div></div>`}
];
const paragraphs=document.getElementById('paragraphs');const quick=document.getElementById('quickParagraphs');const input=document.getElementById('searchInput');const welcome=document.getElementById('welcome');const noResults=document.getElementById('noResults');
function render(){if(!paragraphData.length)return;quick.innerHTML='';paragraphs.innerHTML='';let lastChapter=null;paragraphData.forEach(p=>{if(p.chapter!==lastChapter){const ch=document.createElement('div');ch.style.cssText='width:100%;font-weight:800;color:#173f68;margin:8px 0 2px';ch.textContent='Глава '+p.chapter;quick.appendChild(ch);lastChapter=p.chapter}const b=document.createElement('button');b.textContent='§'+p.number;b.onclick=()=>document.getElementById('p'+p.number)?.scrollIntoView({behavior:'smooth',block:'start'});quick.appendChild(b);const a=document.createElement('article');a.className='paragraph searchable';a.id='p'+p.number;a.dataset.search=(p.search||'')+' '+p.title;a.innerHTML=`<span class="tag">Глава ${p.chapter} · § ${p.number}</span><h2>${p.title}</h2>${p.html}`;paragraphs.appendChild(a)});welcome.classList.add('hidden')}
function clearMarks(){document.querySelectorAll('mark.search-hit').forEach(m=>m.replaceWith(document.createTextNode(m.textContent)));document.body.normalize()}
function highlight(root,q){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())if(walker.currentNode.parentElement&&!walker.currentNode.parentElement.closest('script,style,mark')&&walker.currentNode.nodeValue.toLowerCase().includes(q))nodes.push(walker.currentNode);let first=null;nodes.forEach(n=>{const text=n.nodeValue,re=new RegExp('('+q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')','gi'),frag=document.createDocumentFragment();let last=0;text.replace(re,(m,_g,off)=>{frag.append(text.slice(last,off));const mark=document.createElement('mark');mark.className='search-hit';mark.textContent=m;frag.append(mark);if(!first)first=mark;last=off+m.length});frag.append(text.slice(last));n.replaceWith(frag)});return first}
input.addEventListener('input',()=>{clearMarks();const q=input.value.trim().toLowerCase().replace(/ё/g,'е');const cards=[...document.querySelectorAll('.searchable')];if(!q){cards.forEach(c=>c.classList.remove('hidden'));noResults.style.display='none';return}let shown=0,first=null;cards.forEach(c=>{const text=(c.innerText+' '+c.dataset.search).toLowerCase().replace(/ё/g,'е');const hit=text.includes(q)||(/^\d+$/.test(q)&&c.id==='p'+q);c.classList.toggle('hidden',!hit);if(hit){shown++;first=first||highlight(c,q)}});noResults.style.display=shown?'none':'block';if(first)setTimeout(()=>first.scrollIntoView({behavior:'smooth',block:'center'}),20)});render();