const paragraphData=[];
const paragraphs=document.getElementById('paragraphs');
const quick=document.getElementById('quickParagraphs');
const input=document.getElementById('searchInput');
const welcome=document.getElementById('welcome');
const noResults=document.getElementById('noResults');
function render(){if(!paragraphData.length)return;quick.innerHTML='';paragraphs.innerHTML='';paragraphData.forEach(p=>{const b=document.createElement('button');b.textContent='§'+p.number;b.onclick=()=>document.getElementById('p'+p.number)?.scrollIntoView({behavior:'smooth',block:'start'});quick.appendChild(b);const a=document.createElement('article');a.className='paragraph searchable';a.id='p'+p.number;a.dataset.search=(p.search||'')+' '+p.title;a.innerHTML=`<span class="tag">§ ${p.number}</span><h2>${p.title}</h2>${p.html}`;paragraphs.appendChild(a)});welcome.classList.add('hidden')}
function clearMarks(){document.querySelectorAll('mark.search-hit').forEach(m=>m.replaceWith(document.createTextNode(m.textContent)));document.body.normalize()}
function highlight(root,q){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())if(walker.currentNode.parentElement&&!walker.currentNode.parentElement.closest('script,style,mark')&&walker.currentNode.nodeValue.toLowerCase().includes(q))nodes.push(walker.currentNode);let first=null;nodes.forEach(n=>{const text=n.nodeValue,re=new RegExp('('+q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+')','gi'),frag=document.createDocumentFragment();let last=0;text.replace(re,(m,_g,off)=>{frag.append(text.slice(last,off));const mark=document.createElement('mark');mark.className='search-hit';mark.textContent=m;frag.append(mark);if(!first)first=mark;last=off+m.length});frag.append(text.slice(last));n.replaceWith(frag)});return first}
input.addEventListener('input',()=>{clearMarks();const q=input.value.trim().toLowerCase().replace(/ё/g,'е');const cards=[...document.querySelectorAll('.searchable')];if(!q){cards.forEach(c=>c.classList.remove('hidden'));noResults.style.display='none';return}let shown=0,first=null;cards.forEach(c=>{const text=(c.innerText+' '+c.dataset.search).toLowerCase().replace(/ё/g,'е');const hit=text.includes(q)||(/^\d+$/.test(q)&&c.id==='p'+q);c.classList.toggle('hidden',!hit);if(hit){shown++;first=first||highlight(c,q)}});noResults.style.display=shown?'none':'block';if(first)setTimeout(()=>first.scrollIntoView({behavior:'smooth',block:'center'}),20)});
render();